[theme]
name = "theme name"
version = "0.1.0"
url = "..."

[theme.maintainer]
name = "Shawn O'Hare"
email = "shawn@shawnohare.com"

# Default values are merged into each palette node.
[colors]

[aliases]

[palettes.deep]
# ...
