"""Render templates and write outputs."""

from pathlib import Path
from typing import Callable

import luadata

from jinja2.loaders import PackageLoader
from jinja2.environment import Environment
from jinja2 import StrictUndefined, Template

from loguru import logger
from pydantic import BaseModel

from hadalized.config import Palette, Config


type ContextHandler = Callable[[Palette], Palette | dict]
"""A function that can produce context to provide to a template."""


def model_dump_lua(model: BaseModel) -> str:
    return luadata.serialize(model.model_dump(mode="json"), indent="  ")


class FileWriter:
    """Generate and write files containing hadalized palettes."""

    def __init__(self, config: Config | None = None, target_dir: Path = Path("./")):
        self.config: Config = config or Config()
        self.jenv = Environment(
            loader=PackageLoader("hadalized"),
            undefined=StrictUndefined,
        )
        self.target_dir: Path = target_dir

    def _write_palettes(
        self,
        out_dir: Path,
        template_name: Template | str,
        handler: ContextHandler,
        ext: str = "",
    ):
        """Boilerplate for writing a file for each palette.

        Args:
            out_dir: The directory to output each rendered palette. Prefixed
                with the instance's target_dir.
            template_name: The palette template to use for rendering.
            handler: A callable to convert a palette to template context.
            ext: Optional output file extension.
        """
        out_dir = self.target_dir / out_dir
        out_dir.mkdir(parents=True, exist_ok=True)
        if isinstance(template_name, str):
            tmpl = self.jenv.get_template(template_name)
            _, _, ext = template_name.rpartition(".")
        else:
            tmpl = template_name
        if not ext:
            raise ValueError("No output extension type specified.")
        for palette in self.config.palettes.values():
            path = out_dir / f"{palette.name}.{ext}"
            logger.info(f"Writing {path}")
            context = handler(palette)
            path.write_text(tmpl.render(context))

    def _write_readme(self, out_dir: Path):
        path = self.target_dir / out_dir / "README.md"
        logger.info(f"Writing {path}")
        path.write_text("The files in this directory are autogenerated.")

    def write_html_palettes(self, out_dir: Path = Path("./tmp/html")):
        """Write an html file displaying the colors for each palette."""

        def handler(palette: Palette):
            return palette.css()

        logger.info("Writing html example display palettes.")
        self._write_palettes(out_dir, "palette.html", handler)

    # def write_neovim_palettes(self, out_dir: Path = Path("./lua/hadalized/palettes")):
    #     """Write a lua module containing hex color codes for each palette."""
    #
    #     # WARNING: use static theme files instead of this
    #     logger.warning("")
    #     def handler(palette: Palette):
    #         phex = palette.hex()
    #         palette_dict = phex.model_dump(mode="json")
    #         data = model_dump_lua(phex)
    #         return palette_dict | {"data": data}
    #
    #     logger.info("Writing neovim palette modules.")
    #     self._write_palettes(out_dir, "neovim_palette.lua", handler)
    #     self._write_readme(out_dir)

    def write_neovim_themes(self, out_dir: Path = Path("./colors")):
        """Write a lua module containing defining neovim theme for each palette."""

        def handler(p: Palette):
            return {"data": model_dump_lua(p.hex())}

        logger.info("Writing neovim themes.")
        self._write_palettes(out_dir, "neovim_theme.lua", handler)
        self._write_readme(out_dir)

    def write_wezterm_themes(self, out_dir: Path = Path("./wezterm")):
        """Write a lua module containing defining neovim theme for each palette."""

        def handler(palette: Palette):
            return palette.hex()

        logger.info("Writing wezterm themes.")
        self._write_palettes(out_dir, "wezterm.toml", handler)
        self._write_readme(out_dir)

    def write_json_palettes(self, out_dir: Path = Path("./tmp/json")):
        def handler(p: Palette):
            return {"data": p.model_dump_json(indent=4)}

        template = Template("{{data}}")
        self._write_palettes(out_dir, template, handler, ext="json")

    def write_all(self):
        """Generate all relevant files."""
        self.write_html_palettes()
        self.write_neovim_themes()
        self.write_wezterm_themes()
        self.write_json_palettes()


def main():
    FileWriter().write_all()


if __name__ == "__main__":
    main()
